#!/usr/bin/php
<?php

$commands = array('-l');

if (isset($argv[1])) {
    if (!in_array($argv[1], $commands)) {
        $deploy = $argv[1] . '.ini';
    } else {
        $deploy = 'deploy.ini';
    }
} else {
    $deploy = 'deploy.ini';
}

$opts = getopt("l");

$list = isset($opts['l']);

try {
    $git = new Terra_Git();
    if (!$list) {
        $git->setDeployFile($deploy);
        $git->deploy();
    } else {
        $files = $git->getFilesToUpload();
        if (count($files['upload']) > 0) {
            echo "Files to upload:\n";
            foreach ($files['upload'] as $fileToUpload) {
                echo $fileToUpload . "\n";
            }
        }

        if (count($files['delete']) > 0) {
            echo "Files to delete:\n";
            foreach ($files['delete'] as $fileToDelete) {
                echo $fileToDelete . "\n";
            }
        }
    }
} catch (Exception $e) {
    echo $e->getMessage();
}

class Terra_Git {

    protected $filesToIgnore = array(
        'git-deploy',
        '.gitignore',
    );
    protected $servers = array();

    function setDeployFile($deploy) {
        if (!@file_exists($deploy)) {
            throw new Exception("File '$deploy' does not exist.");
        } else {
            $servers = parse_ini_file($deploy, true);
            if (!$servers) {
                throw new Exception("File '$deploy' is not a valid .ini file.");
            } else {
                $this->addServers($servers);
            }
        }
        $this->ignoreFile($deploy);
    }

    function addServers($servers) {
        foreach ($servers as $uri => $options) {

            if (substr($uri, 0, 6) === 'ftp://') {
                $options = array_merge($options, parse_url($uri));
            }

            # Throw in some default values, in case they're not set.
            $options = array_merge(array(
                'skip' => false,
                'host' => '',
                'user' => '',
                'pass' => '',
                'port' => 21,
                'path' => '/',
                'passive' => true
                    ), $options);

            if ($options['skip']) {
                continue;
            } else {
                $this->servers[$uri] = $options;
            }
        }
    }

    function ignoreFile($file) {
        $this->filesToIgnore[] = $file;
    }

    function getFilesToUpload($targetRevision = null) {
        # Get the list of files to update.

        if (!empty($targetRevision)) {
            $command = "git diff --name-status {$targetRevision}...HEAD";
        } else {
            $command = "git ls-files";
        }

        $output = array();
        exec($command, $output);

        $filesToUpload = array();
        $filesToDelete = array();

        if (!empty($targetRevision)) {
            foreach ($output as $line) {
                if ($line[0] == 'A' or $line[0] == 'C' or $line[0] == 'M') {
                    $filesToUpload[] = trim(substr($line, 1, strlen($line)));
                } elseif ($line[0] == 'D') {
                    $filesToDelete[] = trim(substr($line, 1, strlen($line)));
                } else {
                    throw new Exception("Unknown git-diff status: {$line[0]}");
                }
            }
        } else {
            $filesToUpload = $output;
        }

        foreach ($filesToUpload as $key => $file) {
            if (in_array($file, $this->filesToIgnore)) {
                unset($filesToUpload[$key]);
            }
        }

        return array(
            'upload' => $filesToUpload,
            'delete' => $filesToDelete
        );
    }
    
    function output($message) {
        echo $message;
    }

    function deploy() {
        foreach ($this->servers as $server) {
            $this->deployGitOverFtp($server['host'], $server['user'], $server['pass'], $server['port'], $server['path'], $server['passive']);
        }
    }

    function deployGitOverFtp($host, $user = '', $pass = '', $port = 21, $path = '/', $passive = true) {

        # Let's make sure the $path ends with a slash.

        if (substr($path, strlen($path) - 1, strlen($path)) !== '/') {
            $path = $path . '/';
        }

        $pathsThatExist = array();

        # Okay, let's connect to the server.

        $connection = @ftp_connect($host, $port);

        if (!$connection) {
            throw new Exception("Could not connect to $host.");
        } else {

            if (!@ftp_login($connection, $user, $pass)) {
                throw new Exception("Could not login to $host (Tried to login as $user).");
            }


            ftp_pasv($connection, $passive);

            if (ftp_chdir($connection, $path)) {
                
            } else {
                throw new Exception("Could not change the FTP directory to $path.");
            }

            echo("----------------------------\r\n");
            echo "Connected to {$host}{$path}\r\n";
            echo "----------------------------\r\n";

            # Now that we're logged in to the server, let's get the remote revision.

            $remoteRevision = '';

            $tmpFile = tmpfile();

            if (@ftp_fget($connection, $tmpFile, 'REVISION', FTP_ASCII)) {
                fseek($tmpFile, 0);
                $remoteRevision = trim(fread($tmpFile, 1024));
                fclose($tmpFile);
            } else {
                # Couldn't get the file. I assume it's because the file didn't exist.
            }

            $files = $this->getFilesToUpload($remoteRevision);
            $filesToUpload = $files['upload'];
            $filesToDelete = $files['delete'];
            unset($files);

            foreach ($filesToUpload as $file) {
                # Make sure the folder exists in the FTP server.

                $dir = split("/", dirname($file));
                $path = "";
                $ret = true;

                for ($i = 0; $i < count($dir); $i++) {
                    $path.= $dir[$i] . '/';

                    if (!isset($pathsThatExist[$path])) {
                        $origin = ftp_pwd($connection);

                        if (!@ftp_chdir($connection, $path)) {
                            if (!@ftp_mkdir($connection, $path)) {
                                $ret = false;
                                echo "Failed to create '$path'.\r\n";
                                echo "A problem occurred while attempting to create a folder. Upload to this server cannot continue.\r\n";
                                return;
                            } else {
                                echo "Created directory '$path'.\r\n";
                                $pathsThatExist[$path] = true;
                            }
                        } else {
                            $pathsThatExist[$path] = true;
                        }

                        ftp_chdir($connection, $origin);
                    }
                }

                $uploaded = false;
                $attempts = 1;
                while (!$uploaded) {
                    
                    if ($attempts == 10) {
                        $this->output("Tried to upload $file 10 times, and failed 10 times. Something is wrong, so I'm going to stop executing now.");
                        exit;
                    }
                    
                    # This makes sure to repeat the upload until it finally succeeds.
                    # Hopefully helps fix a problem where some files aren't transferred.
                    $uploaded = @ftp_put($connection, $file, $file, FTP_BINARY);
                    
                    if (!$uploaded) {
                        $attempts = $attempts + 1;
                        $this->output("Failed to upload {$file}. Retrying (attempt $attempts/10)... ");
                    }
                }
                echo "Uploaded {$file}\r\n";
            }

            foreach ($filesToDelete as $file) {
                @ftp_delete($connection, $file);
                echo "Deleted {$file}\r\n";
            }

            if (count($filesToUpload) > 0 or count($filesToDelete) > 0) {
                $temp = tempnam(sys_get_temp_dir(), 'gitRevision');
                file_put_contents($temp, exec('git rev-parse HEAD'));
                ftp_put($connection, 'REVISION', $temp, FTP_BINARY);
                unlink($temp);
                echo "Uploaded REVISION file\r\n";                
            } else {
                echo "No files to upload.";
            }
            
            echo "Finished working on {$host}{$path}\r\n";

            ftp_close($connection);
        }
    }

}